ianstormtaylor/superstruct

package.json, src/superstruct.js, test/index.js, yarn.lock
Importing modules from Lodash via `lodash/*` is rarely a clean import. You need to configure babel/webpack heavily and/or use the [babel plugin](https://www.npmjs.com/package/babel-plugin-lodash), which typically still requires extra config.
Any users who wire up this great lib for Module imports will _also_ need to be aware of the full `lodash` import.
It's far better to just use the modular `lodash.*` packages instead. John David Dalton recommends this too! It's more declarative, and is the most reliable way to avoid needless lodash imports.
For example, these changes alone dropped the 95kB minified file to 61kB! 🎉
=> Migrate to Lodash Modules

Readme.md, src/superstruct.js
Right now everything is done with `struct(...)` where the definition can be for any kind of schema, and it will figure it out automatically. This is super useful for keeping things terse. But some kinds are going to require disambiguation. 
So now the `struct(...)` actually is just a smart wrapper around explicit factories for each kind of object. For example:
```js
struct('string')
struct.scalar('string')
struct(['string'])
struct.list(['string'])
```
This paves the way to be able to support things like `struct.dict` more easily.
=> Refactor struct factory to expose explicit kind functions

package.json, src/default-types.js, src/superstruct.js, yarn.lock
Greatly reduces the dep size, mainly because `lodash.clonedeep` handles a bunch of edge cases and things we don't actually need for our use case.
=> switch clone and type checking deps

docs/reference.md, src/superstruct.js
Changes `validate()` from returning either an error or a result to returning an array that can easily be destructured instead:
```js
const [ error, result ] = Struct.validate(data)
```
Closes #21
=> Return validate array

examples/throwing-errors.js
The value passed in in the example is actually `true` not `false`. So just a quick correction of the example.
=> fix throwing errors example with expected values

src/types.js
Promises are supported in `kind-of` so wanted to see about adding this.
Tested and confirmed with
```
import { struct } from 'superstruct'
const Struct = ({
operation: 'promise'
});
const promiseTest = {
operation: Promise.resolve().then(Promise.resolve())
};
const isValidPromise = Struct(promiseTest);
```
=> Feature: Added promise-type support to default types

config/rollup-umd-min.js, package.json
Closes #69
Currently the minify process is done by browserify plugins. This introduces some building errors mentioned in #69. A simpler solution is to remove these plugins and embrace rollup ecosystem. The output file config of UMD bundle is also missing. This PR simply fixes them.
I've tested in following cases:
* Clean `npm install` works fine without error thown.
* `yarn run build` get minified UMD bundle correctly generated.
* `npm run build:min` also works fine.
As a bonus, maybe it's time for us to remove all browserify dependencies. For a pure JS library I haven't found the case to favor it instead of rollup.
Notes:
1. There's some trouble for my network updating `package-lock.json` and `yarn.lock`. Any ideas refreshing them?
2. There's a known issue for uglify.js to minify ES2015. …
=> Replace uglifyify with rollup plugin

config/rollup-umd.js
In #68 following error thrown in JSFiddle: 
```
superstruct.js:275 Uncaught ReferenceError: process is not defined
at any (VM82 superstruct.js:275)
at list (VM82 superstruct.js:550)
at any (VM82 superstruct.js:234)
at object (VM82 superstruct.js:633)
at Object.any (VM82 superstruct.js:244)
at struct (VM82 superstruct.js:1063)
at window.onload ((index):66)
```
This is due to `process.env.NODE_ENV` is preserved in UMD build, keeping this variable in browser leads to an error.
To my understanding, following strategy is ideal for `NODE_ENV`:
So this PR implements the last missing point. With `rollup-plugin-replace` we can easily achieve this without modifying code in `src`.
=> Strip out NODE_ENV in UMD build

docs/reference.md
This PR ensures all API under `#structs` links to existing item in alphabetical order.
P.S. There are still some missing `Structs` validator missing in reference manual. Are these kinds designed to be private? I did a quick search and have the following list for missing items:
=> Fix doc catalog href

src/error.js
This closes #94 as suggested, but I think I'd prefer my initial approach since this is a bit hacky & still requires importing the entire class object to access the formatter.
It's your call, but ideally, I'd do this:
```js
export function formatError(attrs) {
// ...same
}
export class StructError extends TypeError {
constructor(attrs) {
const msg = formatError(attrs)
super(msg)
const errors = attrs.errors || []
// ...same
}
}
// ---
import { formatError, StructError } from './error'
export {
struct,
superstruct,
isStruct,
formatError,
StructError
}
```
```js
import { formatError } from 'superstruct';
```
=> Add static 'format' method on StructError

src/kinds.js, test/fixtures/dict-scalars/defaults-subset.js, test/fixtures/interface/defaults-structs.js, test/fixtures/interface/defaults-subset.js, test/index.js
dict and interface defaults subset fix
interfaces composed of structs with their own defaults now resolve those defaults
Also adds .only and .skip support for individual tests (by exports)
I think it closes #104
=> dict, interface defaults subset

src/types.js, test/fixtures/built-ins/date-invalid-date.js, test/fixtures/built-ins/date-invalid.js, test/fixtures/built-ins/date-valid.js, test/fixtures/built-ins/number-invalid.js, test/fixtures/built-ins/number-valid.js, test/fixtures/built-ins/string-invalid.js, test/fixtures/built-ins/string-valid.js
Fixes #115 by erroring on invalid `Date` objects.
=> fix to throw out invalid date objects

src/kinds.js
#111
Currently only the first error of a sub struct (e.g. list) is included in the parent object struct.
TDB if there are more implications for other struct kinds. Further the testsuite has to be extended for this.
cheers
=> pass all errors of composed structs for #111

docs/reference.md, src/kinds.js, test/fixtures/dynamic/defaults.js, test/fixtures/dynamic/invalid.js, test/fixtures/dynamic/nested-list-invalid.js, test/fixtures/dynamic/nested-list.js, test/fixtures/dynamic/optional.js, test/fixtures/dynamic/reference.js, test/fixtures/dynamic/valid.js, test/fixtures/lazy/defaults.js, test/fixtures/lazy/invalid.js, test/fixtures/lazy/optional.js, test/fixtures/lazy/valid.js
I've come across a use case where I needed to validate many possible structs in a tree-like data structure.  
I've managed to accomplish that by abusing the custom type system:
<details><summary>Code example <b>(click to expand)</b></summary>
```javascript
import {superstruct, struct} from 'superstruct'
const base = struct({'someValue': 'boolean'})
export const Struct = superstruct({
'types': {
'base': base.test,
}
})('base')
```
</details>
While this works as far as validation of the correctness is concerned, I lose the awesome error messages Superstruct generates. This is because the error will contain the fact that only the topmost element in my data tree is incorrect. I'd expect the path to drill down to the lowest level and then work its way up the tree.  
This PR contains a …
=> Dynamic structs

src/kinds.js, test/fixtures/dynamic/nested-list-invalid.js
Previously nested errors messages would describe the parent type of a nested error, rather than the type of the field that actually failed to validate.  This isn't exactly inaccurate (a parent is invalid if a child is invalid), but not very helpful for identifying errors in these circumstances.  
Example previously:
> Error message: "Expected a value of type `[{SectionType1,SectionType2,SectionType3} | undefined | null] | undefined | null` for `sections.0.blockInputTypeA.0.notes` but received `undefined`."
The equivalent error now reads:
> Error message: "Expected a value of type `String` for `sections.0.blockInputTypeA.0.notes` but received `undefined`."
Which more accurately reports the actual field that failed to validate.
=> Provides better error messages for nested errors

src/kinds.js, test/fixtures/interface/invalid-nested.js, test/fixtures/interface/invalid.js, test/fixtures/interface/valid-object-instance.js
Added a validation to check if a `interface` is an object before checking it's properties.
This validation was taken from `partial`.
Test fixture added.
One fixture had to be changed because it's expected error was wrong.
Fixes #119
=> Validate that an interface is an object before checking it's properties

docs/guide.md, package.json
As per https://github.com/ianstormtaylor/superstruct/issues/377
With respect to the documentation, I import the wildcard as `be` which is what my library was called but the reason is that it is fairly descriptive. e.g. `be.optional(be.string())`. It also doesn't conflict with other methods like `is`.
However, that's a personal choice. I can change it to something else like `ss` so we'd end up with `ss.optional(ss.string())`.
=> Added import using wildcard to docs

docs/guide.md, package.json
Added a section describing how to use generics with custom types and how to use the `StructType` utility.
=> Add TypeScript info to Docs

package.json, src/types.ts, test/types/object.ts, test/types/optional.ts
The purpose of the PR is to make `object()` types with `optional()` values appear as optional properties on an object. e.g.
```ts
// given
const struct = object({ a: optional(string()) })
// it should return this type (the `?` being the key change)
type X = {
a?: string | undefined
}
```
There is also a related change to `package.json` which adds a script `watch:types`.  The purpose of this script is so that when there are changes to code, the TypeScript type definitions get updated. During the normal `watch`, type changes are not reflected. A better solution may be to add `build:types` as part of the `watch` script instead of in a separate `watch:types` script.
Stylistically, the type helpers are near the `object` code. There aren't any existing type helpers (at least in the code I saw) …
=> Optional properties

docs/reference.md
Thanks for the great library!
While reading the new documentation to update a version I re-read the section on `record` and applied the syntax as given in the document. However, TypeScript complained and when looking at the test it's clear that the docs are incorrect on this one:
https://github.com/ianstormtaylor/superstruct/blob/master/test/types/record.ts
=> chore(docs): Update `record` entry

docs/reference.md
Right now implementation of `partial` contradicts its description in docs. Current behavior:
```ts
assert(
{ a:1 },
partial({ a: number(), b: number() }),
) // ok
```
See https://github.com/ianstormtaylor/superstruct/issues/405#issuecomment-687128744
Fixes https://github.com/ianstormtaylor/superstruct/issues/405
=> Fix partial reference docs

docs/reference.md
- Removes erroneous semicolon
- Moves two examples to separate lines
- Uses `id: number() -> { id: 1 }` instead of `id: string() -> id: '1'` because I felt that comprehension required _slightly_ more mental gymnastics when the id string happened to also be numerical.
=> Update reference docs on `array`

src/structs/types.ts
See https://github.com/ianstormtaylor/superstruct/issues/523
=> Use `readonly` modifier in enums to accept readonly const arrays

Readme.md
Uses the non-deprecated version in the getting started example.
=> Fix README: `struct` => `define`

docs/reference/coercions.md, docs/reference/types.md, src/struct.ts, src/utils.ts, test/api/mask.ts
- Make mask() and Struct.mask() running masking recursively, fixes #618
- Let type() still keep unknown props when mask() mode is used, fixes #619
- Add unit tests
- Add a couple more sentences to the docs
- Do not remove masked() coercion for backward compatibility reasons (it may still be useful)
=> make mask() recursive, allow type() pass unknown properties through in mask=true mode

docs/readme.md
Replaced the use of the deprecated `struct` function in favor of `define`.
Instead of incrementing the not declared variable `i`, in my opinion the example on line 70 gets the point across better if it's self sufficient - you can copy and paste it and it works.
=> docs: replaced deprecated with current API use in introduction docs

src/structs/types.ts, src/utils.ts, test/typings/describe.ts
Small PR to fix some interesting false error cases of using describe with literal types:
```ts
const a: Describe<1 | 2 | 3> = enums([1, 2, 3]) // type error
const b: Describe<'1' | '2' | '3'> = enums(['1', '2', '3']) // works
const c: Describe<'test'> = literal('test') // type error
const d: Describe<1'> = literal(1) // works
```
I've added tests for the failing cases, with the fix being to provide the same schema type as `enum` when using `literal`.
=> fix: fixed describe for some literal types

Readme.md
Follow up to https://github.com/ianstormtaylor/superstruct/pull/595. Seems that the `struct` import has been overseen?
=> Readme: `struct` => `define` in usage example

docs/reference/refinements.md
there doesn't seem to be a `below` export
=> docs(refinements): `below` -> `max`

src/structs/types.ts, test/validation/union/coercion-nested.ts, test/validation/union/coercion.ts
Previously union types were not coerced due to the ambiguous behavior that might result. There may
be multiple Structs in a union that could coerce a given value (for example, defaulted(string()) and
defaulted(number()) would both successfully coerce an undefined value). This change takes an opinion
that the first Struct passed that can be coerced into a valid object from the passed value shall
take precedence, allowing coercion to occur in some form, even if its opinionated
resolves #580
---
I've left out docs until this approach is approved overall. The tests illustrate what happens, but basically it optimistically assumes the first valid coercing struct that is passed into the union is the right one to use *for coercion* A _coercable_ value does not pass validation after this …
=> feat(union): add support for coercion of union types

examples/custom-errors.js
Based on the example, expected value for line 44 should be `true`, not `false`.
=> fix expected output value

docs/reference/types.md
Took me a while to figure this out, so I thought it might be worthwhile to add it to the docs.
=> types.md: Explain how to set the Typescript type when using define()

src/utils.ts
Fix for #693 
To be honest, simply adding undefined feels kind of wrong in this case. But it was the only solution I came up with and as far as my few tests sufficed, it yields correct types and `npm run test` doesn't complain either.
=> Allow optional enums

docs/reference/types.md
This PR fixes an issue with the example code for `object`. It should use the `object` function instead of the `struct` function.
=> Change `struct()` to `object()` in `object` docs

src/structs/utilities.ts, test/validation/dynamic/with-refiners.ts, test/validation/lazy/with-refiners.ts
This PR fixes the refiners being previously ignored in the structs returned by `lazy` and `dynamic` utilities.
I have added 2 new test cases that prove the refiners work now.
Fixes #830
=> Respect refiner in `dynamic` and `lazy`

src/utils.ts, test/api/validate.ts, test/validation/refine/invalid-multiple-refinements.ts
Previously refiners ran only when there were no past failures during
validation of the value itself or its subvalues. This behavior was
causing inferior UX when validating forms with additional validations
defined as refiners. If there was a refinement error in some subfield,
the refiners defined on the parent of that subfield were not executed.
Only after fixing the error in the subfield did the user receive
information about the failure on the parent field.
This commit changes the condition under which refinements are run.
Refinements are executed if there were no previous failures or those
failures came exclusively from other refiners.
The change helps in the form validation scenario because as long as the
form structure is valid (which is checked using `validator`s), failures
from all …
=> Run refiners as long as validators passed

src/utils.ts, test/api/create.ts
While using create to coerce some data, optional fields are defined to undefined values.
This causes problems when storing the result directly in MongoDB (generates null values).
The PR removes these undefined fields from the result of the create call.
Fix for #981
=> Stop coercing empty optional fields to undefined values

.github/workflows/ci.yml, config/rollup.js, package.json
It appears that between 0.16.0 and 0.16.1, the minimum version of Node required to use this package changed, from 14.x to 16.x. This was not explicit but seems to have been caused by a couple of factors.
But first, what changed. If you look at `src/error.ts` in 0.16.0 you will see [this line][1]:
```
return (cached ??= [failure, ...failures()])
```
In the [published version of this file in 0.16.0][2] this gets transpiled to:
```
return (_cached = cached) != null ? _cached : cached = [failure, ...failures()];
```
In 0.16.1, the [original line is unchanged][3], but in the [published version][4] it is transpiled to:
```
return cached ??= [failure, ...failures()];
```
The `??=` syntax is not supported by Node 14, hence, developers are forced to upgrade to at least Node 16 if they want to use …
=> Support Node 14 (again)

docs/reference/refinements.md
As per https://github.com/ianstormtaylor/superstruct/issues/1095.
Note that I also added a short "robot tip" about the typing of refiner function's `value`, as I felt it might be reassuring to know that `value.startDate < value.endDate` is guaranteed to be safe.
=> Document custom error messages for refinements

src/utils.ts, test/api/create.ts
Closes #1125 
Ensures explicit undefined values in coercions are respected. (See linked issue for details)
This is my first time contributing, so let me know if you'd like anything done differently.
=> Allow coercions to undefined

src/utils.ts
Fixes #1134.
Doing \`${Symbol('foo')}\` results in "TypeError: Cannot convert a Symbol value to a string". Using `Symbol('foo').toString()` works however, and results in the string `"Symbol(foo)"`.
=> Fix Symbol serialisation

src/utils.ts
I'd like to add `nullable` in [this](https://github.com/ianstormtaylor/superstruct/pull/694) case.
I couldn't find any problems with following:
```bash
yarn test
```
and
```ts
const undefinedTestTypeSchema: Describe<undefined> = literal(undefined)
const nullTestTypeSchema: Describe<null> = literal(null)
const optionalTestTypeSchema: Describe<string | undefined> = optional(string())
const partialEnumTypeSchema: Describe<{ foo?: 'bar' | 'baz' }> = object({
foo: optional(enums(['bar', 'baz'] as const)),
})
const partialAndNullableEnumTypeSchema: Describe<{
foo?: 'bar' | 'baz' | null
}> = object({
foo: optional(nullable(enums(['bar', 'baz'] as const))),
})
const nullableEnumTypeSchema: Describe<{
foo: 'bar' | 'baz' | null
}> = object({
foo: nullable(enums(['bar', 'baz'] as const)),
})
const …
```
=> Allow optional and nullable enums

docs/reference/utilities.md
Noticed that `omit` is missing the mention of `type` whilst writing #1149.
=> Document the usage of the type struct in the omit utility

docs/reference/utilities.md, src/structs/utilities.ts, test/validation/partial/valid-type.ts, test/validation/pick/valid-type.ts
=> Retain struct's type in partial and pick helpers

docs/guides/02-validating-data.md, docs/guides/03-coercing-data.md, docs/guides/04-refining-validation.md, docs/guides/06-using-typescript.md
Many of the examples in the docs have some imports but not all. That was confusing for me, especially because `assert` exists in std lib of Node.js.
This PR doesn't thrive do make all examples copy-pasteable, only the ones that already had import declarations by making the list of imports complete.
=> make more of the examples runnable

test/api/assert.test.ts, test/api/create.test.ts, test/api/is.test.ts, test/api/mask.test.ts, test/api/validate.test.ts, test/deprecated.test.ts, test/index.test.ts
In this PR, the test suite has been modified:
- `deepStrictEqual` and `deepEqual` have been changed to `.toStrictEqual` for objects and arrays and `.toBe` for literals.
- Moved the deprecated tests to their own file.
- I've opted to keep the usage of `throws` and `doesNotThrow` because it offers a nicer api to check whether an error was thrown or not than the Jesty `expect` solution.
- [Expect documentation from Vitest](https://vitest.dev/api/expect.html) for your reference!
#1244
=> Use Vitest and expect methods for testing suite

examples/README.md, examples/package.json, package.json, test/@types/is-email.d.ts, test/validation/refine/invalid.ts, test/validation/refine/valid.ts
Removing `is-email` from the testing suite. Its used as a dev dependency only when testing `refine`, and it creates some complexity because we need to type that function. Not worth it in my opinion!
Related: #1244
=> Remove "is-email" from testing suite

package.json
Related: #1244
Adding a script to `package.json` to allow the testing suite to be run in watch mode. It will automatically re-run the testing suite when a file is updated.
=> Allow users to run the testing suite in watch mode

docs/readme.md
=> docs: correct Type(s|S)cript typo in docs/readme.md

src/structs/types.ts, test/validation/array/valid-frozen.ts, test/validation/object/valid-frozen.ts, test/validation/record/valid-frozen.ts, test/validation/tuple/valid-frozen.ts, test/validation/type/valid-frozen.ts
The issue was the [mutation of the input object/array](https://github.com/ianstormtaylor/superstruct/blob/03d65bd37d505d934db7cb48eed691fc41ecba7c/src/utils.ts#L185) while coercing entries inside the `run` util -- combined with a missing custom coercer which would clone its input (exactly as @gwisp2 suggested in #1096).
Apart from `record`, `tuple` was also affected by the same potential issue.
1. Added coercer that clones its input to `record` and `tuple`.
1. Added tests with frozen objects for all structs which _could_ potentially be affected (object/array based and include entries).
---
Resolves #1096
=> Allow frozen objects/arrays to be coerced
